### PR TITLE
fix: update PlaybackSpeed when changing the IsPaused flag

### LINKED ISSUE #104: "Pause" doesn't appear to send the correct paused state
So here's a minor issue I'm having.

When you press "pause" in Spotify Android (when connected to go-librespot), it pauses as expected. But when you wait a few seconds (10 or so) and resume, you can see it jumps for a very short time to the time it would have been had the player not been paused. This only happens for a split second, presumably because go-librespot sends an updated position when resuming.

When testing the same thing when connected to open.spotify.com (playing on open.spotify.com, controlled from Spotify Android), this does not happen. So it appears that open.spotify.com sends something different.

I looked at the message it sends to the API and it sends the following request when the web player is being paused:

method: PUT
URL: https://gew4-spclient.spotify.com/track-playback/v1/devices/aeab3d432a2699430b795a799b2dc54f7faa94e4/state
Body:
```json
{
  "seq_num": 1727713694878,
  "state_ref": {
    "state_machine_id": "ChRH6ArMoOoPq_qqG9SoDgTzND1m8A",
    "state_id": "d6ca1a4d3e6d41beb60276fa399afffa",
    "paused": true
  },
  "sub_state": {
    "playback_speed": 0,
    "position": 74994,
    "duration": 424481,
    "media_type": "AUDIO",
    "bitrate": 256000,
    "audio_quality": "VERY_HIGH",
    "format": 11
  },
  "previous_position": 74994,
  "debug_source": "pause"
}
```

`sub_state` looks like PlayerState but for the rest I couldn't find an appropriate protobuf.
Also, there are a ton of fields I don't know the meaning of (such as `seq_num` and `state_machine_id`).

I guess I could try sending this as JSON, to see whether it works at all. If so, I could try to find (or reverse engineer) the protobuf.

@devgianlu do you maybe have any ideas?

### PR DESCRIPTION
**Pull request by aykevl**
The PlaybackSpeed field must be set to 0 when paused. Otherwise Spotify Android will correctly show the stream as paused but will still move the playback position when redrawing the UI (and for a very short time when resuming playback).

Fixes #104

### CODE REVIEW

File: cmd/daemon/player.go [hunk 1]
```diff
@@ -151,21 +151,16 @@ func (p *AppPlayer) handlePlayerCommand(req dealer.RequestPayload) error {
...
 		p.state.player.Timestamp = transferState.Playback.Timestamp
 		p.state.player.PositionAsOfTimestamp = int64(transferState.Playback.PositionAsOfTimestamp)
-		p.state.player.IsPaused = transferState.Playback.IsPaused
-
-		if playbackSpeed := transferState.Playback.PlaybackSpeed; playbackSpeed != 0 {
-			p.state.player.PlaybackSpeed = playbackSpeed
-		} else {
-			p.state.player.PlaybackSpeed = 1
-		}
+		p.state.setPaused(transferState.Playback.IsPaused)
```
Comment (aykevl) [inline cmd/daemon/player.go:163]: I tried testing this, but switching playback over from Spotify Android (for example) to go-librespot appears to be somewhat broken even before this change.

File: cmd/daemon/player.go [hunk 2]
```diff
@@ -452,7 +447,7 @@ func (p *AppPlayer) handleApiRequest(req ApiRequest) (any, error) {
 		}
 
 		p.state.setActive(true)
-		p.state.player.PlaybackSpeed = 1
+		p.state.setPaused(data.Paused)
```
Comment (aykevl) [inline cmd/daemon/player.go:450]: I don't see `IsPaused` getting updated here, while I think it should be. But `PlaybackSpeed` is. I think it is more correct to update both at the same time.

Untested, though.

**Review by aykevl — COMMENTED** [review]
Self-review.

File: cmd/daemon/player.go (hunk 1 above)
Comment (devgianlu) [reply cmd/daemon/player.go:163]: `no primary stream` sounds like a very strange issue for such small changes. Perhaps it is unrelated? `primaryStream` goes nil only when the device goes inactive or just before another track is loaded.

FYI, the logic removed here was required to fix a bug in the progress bar not moving (16741acf9823433324802d7e40624259a7ae99cf). I don't see a regression with this approch, just wanted to mention it.

**Review by devgianlu — APPROVED** [review]
